In [ ]:
!pip install tensorflow_gpu==1.15.5

     |████████████████████████████████| 411.0 MB 25 kB/s 
     |████████████████████████████████| 3.8 MB 52.9 MB/s 
     |████████████████████████████████| 20.1 MB 1.1 MB/s 
     |████████████████████████████████| 503 kB 54.0 MB/s 
     |████████████████████████████████| 2.9 MB 56.6 MB/s 
     |████████████████████████████████| 50 kB 6.8 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=1b67a1350f8752040d481cd519ca44689acfffdfe2810f4115a7eb7573eba05d
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5
  Attempting uninstall: h5py
    Found existing installation: h5py 3.1.0
    Uninstalling h5py-3.1.0:
      Successfully uninstalled h5py-3.1.0
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tenso

In [ ]:
!pip install numpy==1.18.5
!pip uninstall -y pycocotools
!pip install pycocotools --no-binary pycocotools

Found existing installation: pycocotools 2.0.4
Uninstalling pycocotools-2.0.4:
  Successfully uninstalled pycocotools-2.0.4
     |████████████████████████████████| 106 kB 8.9 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for pycocotools: filename=pycocotools-2.0.4-cp37-cp37m-linux_x86_64.whl size=265221 sha256=13f65d8291443fcc24fcf1172a3fb4e71349220428bc66d8dd4c954614effb05
  Stored in directory: /root/.cache/pip/wheels/a3/5f/fa/f011e578cc76e1fc5be8dce30b3eb9fd00f337e744b3bba59b
Successfully built pycocotools


In [ ]:
# use TF 1.x
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
!pip list

Package                       Version
----------------------------- ---------------------
absl-py                       1.0.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.2.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.11.4
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.4.0
audioread                     2.1.9
autograd                      1.3
Babel                         2.9.1
backcall                      0.2.0
backports.tempfile            1.0
backports.weakref             1.0.post1
beautifulsoup4                4.6.3
bleach                        4.1.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.4
bran

In [ ]:
# If you forked the repo, you can replace the link.
repo_url = 'https://github.com/roboflow-ai/tensorflow-object-detection-faster-rcnn'

# Number of training steps - 1000 will train very quickly, but more steps will increase accuracy.
num_steps = 500  # 200000 to improve

# Number of evaluation steps.
num_eval_steps = 100

MODELS_CONFIG = {
    'ssd_mobilenet_v2': {
        'model_name': 'ssd_mobilenet_v2_coco_2018_03_29',
        'pipeline_file': 'ssd_mobilenet_v2_coco.config',
        'batch_size': 16
    },
    'faster_rcnn_inception_v2': {
        'model_name': 'faster_rcnn_inception_v2_coco_2018_01_28',
        'pipeline_file': 'faster_rcnn_inception_v2_pets.config',
        'batch_size': 12
    },
    'rfcn_resnet101': {
        'model_name': 'rfcn_resnet101_coco_2018_01_28',
        'pipeline_file': 'rfcn_resnet101_pets.config',
        'batch_size': 8
    }
}

# Pick the model you want to use
# Select a model in `MODELS_CONFIG`.
selected_model = 'ssd_mobilenet_v2'

# Name of the object detection model to use.
MODEL = MODELS_CONFIG[selected_model]['model_name']

# Name of the pipline file in tensorflow object detection API.
pipeline_file = MODELS_CONFIG[selected_model]['pipeline_file']

# Training batch size fits in Colabe's Tesla K80 GPU memory for selected model.
batch_size = MODELS_CONFIG[selected_model]['batch_size']

In [ ]:
import os

%cd /content

repo_dir_path = os.path.abspath(os.path.join('.', os.path.basename(repo_url)))

!git clone {repo_url}
%cd {repo_dir_path}
!git pull

/content
Cloning into 'tensorflow-object-detection-faster-rcnn'...
remote: Enumerating objects: 885, done.
remote: Total 885 (delta 0), reused 0 (delta 0), pack-reused 885
Receiving objects: 100% (885/885), 24.83 MiB | 30.20 MiB/s, done.
Resolving deltas: 100% (428/428), done.
/content/tensorflow-object-detection-faster-rcnn
Already up to date.


In [ ]:
%cd /content
!git clone --quiet https://github.com/tensorflow/models.git

!pip install tf_slim

!apt-get install -qq protobuf-compiler python-pil python-lxml python-tk

!pip install -q Cython contextlib2 pillow lxml matplotlib

!pip install -q pycocotools

!pip install lvis

%cd /content/models/research
!protoc object_detection/protos/*.proto --python_out=.

import os
os.environ['PYTHONPATH'] += ':/content/models/research/:/content/models/research/slim/'

!python object_detection/builders/model_builder_test.py

/content
     |████████████████████████████████| 352 kB 7.5 MB/s 
Selecting previously unselected package python-bs4.
(Reading database ... 156210 files and directories currently installed.)
Preparing to unpack .../0-python-bs4_4.6.0-1_all.deb ...
Unpacking python-bs4 (4.6.0-1) ...
Selecting previously unselected package python-pkg-resources.
Preparing to unpack .../1-python-pkg-resources_39.0.1-2_all.deb ...
Unpacking python-pkg-resources (39.0.1-2) ...
Selecting previously unselected package python-chardet.
Preparing to unpack .../2-python-chardet_3.0.4-1_all.deb ...
Unpacking python-chardet (3.0.4-1) ...
Selecting previously unselected package python-six.
Preparing to unpack .../3-python-six_1.11.0-2_all.deb ...
Unpacking python-six (1.11.0-2) ...
Selecting previously unselected package python-webencodings.
Preparing to unpack .../4-python-webencodings_0.5-2_all.deb ...
Unpacking python-webencodings (0.5-2) ...
Selecting previously unselected package python-html5lib.
Preparing to un

In [ ]:
!unzip -q /content/drive/MyDrive/ssddataset.zip -d /content/tensorflow-object-detection-faster-rcnn

In [ ]:
!unzip -q /content/drive/MyDrive/dataujissd.zip -d /content/tensorflow-object-detection-faster-rcnn/datauji

In [ ]:
# Create train data:
!python /content/generate_tfrecord.py -x /content/tensorflow-object-detection-faster-rcnn/ssddataset/train -l /content/tensorflow-object-detection-faster-rcnn/data/label_map.pbtxt -o /content/tensorflow-object-detection-faster-rcnn/data/train.record

Successfully created the TFRecord file: /content/tensorflow-object-detection-faster-rcnn/data/train.record


In [ ]:
# Create test data:
!python /content/generate_tfrecord.py -x /content/tensorflow-object-detection-faster-rcnn/ssddataset/test -l /content/tensorflow-object-detection-faster-rcnn/data/label_map.pbtxt -o /content/tensorflow-object-detection-faster-rcnn/data/test.record

Successfully created the TFRecord file: /content/tensorflow-object-detection-faster-rcnn/data/test.record


In [ ]:
test_record_fname = '/content/tensorflow-object-detection-faster-rcnn/data/test.record'
train_record_fname = '/content/tensorflow-object-detection-faster-rcnn/data/train.record'
label_map_pbtxt_fname = '/content/tensorflow-object-detection-faster-rcnn/data/label_map.pbtxt'

In [ ]:
%cd /content/models/research

import os
import shutil
import glob
import urllib.request
import tarfile
MODEL_FILE = MODEL + '.tar.gz'
DOWNLOAD_BASE = 'http://download.tensorflow.org/models/object_detection/'
DEST_DIR = '/content/models/research/pretrained_model'

if not (os.path.exists(MODEL_FILE)):
    urllib.request.urlretrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)

tar = tarfile.open(MODEL_FILE)
tar.extractall()
tar.close()

os.remove(MODEL_FILE)
if (os.path.exists(DEST_DIR)):
    shutil.rmtree(DEST_DIR)
os.rename(MODEL, DEST_DIR)

!echo {DEST_DIR}
!ls -alh {DEST_DIR}

fine_tune_checkpoint = os.path.join(DEST_DIR, "model.ckpt")
fine_tune_checkpoint

/content/models/research
/content/models/research/pretrained_model
total 135M
drwxr-xr-x  3 345018 89939 4.0K Mar 30  2018 .
drwxr-xr-x 23 root   root  4.0K Apr  7 01:33 ..
-rw-r--r--  1 345018 89939   77 Mar 30  2018 checkpoint
-rw-r--r--  1 345018 89939  67M Mar 30  2018 frozen_inference_graph.pb
-rw-r--r--  1 345018 89939  65M Mar 30  2018 model.ckpt.data-00000-of-00001
-rw-r--r--  1 345018 89939  15K Mar 30  2018 model.ckpt.index
-rw-r--r--  1 345018 89939 3.4M Mar 30  2018 model.ckpt.meta
-rw-r--r--  1 345018 89939 4.2K Mar 30  2018 pipeline.config
drwxr-xr-x  3 345018 89939 4.0K Mar 30  2018 saved_model


'/content/models/research/pretrained_model/model.ckpt'

In [ ]:
import os
pipeline_fname = os.path.join('/content/models/research/object_detection/samples/configs/', pipeline_file)

assert os.path.isfile(pipeline_fname), '`{}` not exist'.format(pipeline_fname)

# Helper function to get the total number of classes for the detection task
def get_num_classes(pbtxt_fname):
    from object_detection.utils import label_map_util
    label_map = label_map_util.load_labelmap(pbtxt_fname)
    categories = label_map_util.convert_label_map_to_categories(
        label_map, max_num_classes=90, use_display_name=True)
    category_index = label_map_util.create_category_index(categories)
    return len(category_index.keys())
  
  
import re

num_classes = get_num_classes(label_map_pbtxt_fname)
with open(pipeline_fname) as f:
    s = f.read()
with open(pipeline_fname, 'w') as f:
    
    # fine_tune_checkpoint
    s = re.sub('fine_tune_checkpoint: ".*?"',
               'fine_tune_checkpoint: "{}"'.format(fine_tune_checkpoint), s)
    
    # tfrecord files train and test.
    s = re.sub(
        '(input_path: ".*?)(train.record)(.*?")', 'input_path: "{}"'.format(train_record_fname), s)
    s = re.sub(
        '(input_path: ".*?)(val.record)(.*?")', 'input_path: "{}"'.format(test_record_fname), s)

    # label_map_path
    s = re.sub(
        'label_map_path: ".*?"', 'label_map_path: "{}"'.format(label_map_pbtxt_fname), s)

    # Set training batch_size.
    s = re.sub('batch_size: [0-9]+',
               'batch_size: {}'.format(batch_size), s)

    # Set training steps, num_steps
    s = re.sub('num_steps: [0-9]+',
               'num_steps: {}'.format(num_steps), s)
    
    # Set number of classes num_classes.
    s = re.sub('num_classes: [0-9]+',
               'num_classes: {}'.format(num_classes), s)
    f.write(s)
    
# Viewing the pipeline
!cat {pipeline_fname}

model_dir = 'training/'
# Optionally remove content in output model directory to fresh start.
!rm -rf {model_dir}
os.makedirs(model_dir, exist_ok=True)

# SSD with Mobilenet v2 configuration for MSCOCO Dataset.
# Users should configure the fine_tune_checkpoint field in the train config as
# well as the label_map_path and input_path fields in the train_input_reader and
# eval_input_reader. Search for "PATH_TO_BE_CONFIGURED" to find the fields that
# should be configured.

model {
  ssd {
    num_classes: 2
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_

# Train and Eval Model

In [ ]:
!python /content/models/research/object_detection/model_main.py \
    --pipeline_config_path={pipeline_fname} \
    --model_dir={model_dir} \
    --alsologtostderr \
    --num_train_steps={num_steps} \
    --num_eval_steps=25

Using TensorFlow backend.
W0407 01:34:08.687649 139627316963200 model_lib.py:839] Forced number of epochs for all eval validations to be 1.
INFO:tensorflow:Maybe overwriting train_steps: 500
I0407 01:34:08.687853 139627316963200 config_util.py:552] Maybe overwriting train_steps: 500
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I0407 01:34:08.687962 139627316963200 config_util.py:552] Maybe overwriting use_bfloat16: False
INFO:tensorflow:Maybe overwriting sample_1_of_n_eval_examples: 1
I0407 01:34:08.688044 139627316963200 config_util.py:552] Maybe overwriting sample_1_of_n_eval_examples: 1
INFO:tensorflow:Maybe overwriting eval_num_epochs: 1
I0407 01:34:08.688147 139627316963200 config_util.py:552] Maybe overwriting eval_num_epochs: 1
W0407 01:34:08.688251 139627316963200 model_lib.py:855] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
INFO:tensorflow:create_estimator_and_inputs: us

# Train and Test Model

In [ ]:
# Create test data:
!python /content/generate_tfrecord.py -x /content/tensorflow-object-detection-faster-rcnn/datauji -l /content/tensorflow-object-detection-faster-rcnn/data/label_map.pbtxt -o /content/tensorflow-object-detection-faster-rcnn/data/test.record

Successfully created the TFRecord file: /content/tensorflow-object-detection-faster-rcnn/data/test.record


## Using Last Checkpoint

In [ ]:
!python /content/models/research/object_detection/legacy/eval.py --pipeline_config_path={pipeline_fname} --eval_dir=/content/models/research/training/eval_1 --checkpoint_dir=/content/models/research/training --alsologtostderr

Using TensorFlow backend.
Instructions for updating:
Use object_detection/model_main.py.
W0407 01:41:44.398436 139708117907328 deprecation.py:323] From /usr/local/lib/python3.7/dist-packages/absl/app.py:258: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
INFO:tensorflow:Reading unweighted datasets: ['/content/tensorflow-object-detection-faster-rcnn/data/test.record']
I0407 01:41:44.417296 139708117907328 dataset_builder.py:162] Reading unweighted datasets: ['/content/tensorflow-object-detection-faster-rcnn/data/test.record']
INFO:tensorflow:Reading record datasets for input file: ['/content/tensorflow-object-detection-faster-rcnn/data/test.record']
I0407 01:41:44.418133 139708117907328 dataset_builder.py:79] Reading record datasets for input file: ['/content/tensorflow-object-detection-faster-rcnn/data/test.record']
INFO:tensorflow:Number of filenames to read: 1
I0407 01:41:44.418261 13970811790

## Using Saved Model

In [17]:
!python /content/models/research/object_detection/legacy/eval.py --pipeline_config_path=/content/models/research/fine_tuned_model/pipeline.config --eval_dir=/content/models/research/fine_tuned_model/eval_0 --checkpoint_dir=/content/models/research/fine_tuned_model --alsologtostderr

Using TensorFlow backend.
Instructions for updating:
Use object_detection/model_main.py.
W0407 01:53:56.860350 140686801659776 deprecation.py:323] From /usr/local/lib/python3.7/dist-packages/absl/app.py:258: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
INFO:tensorflow:Reading unweighted datasets: ['/content/tensorflow-object-detection-faster-rcnn/data/test.record']
I0407 01:53:56.879154 140686801659776 dataset_builder.py:162] Reading unweighted datasets: ['/content/tensorflow-object-detection-faster-rcnn/data/test.record']
INFO:tensorflow:Reading record datasets for input file: ['/content/tensorflow-object-detection-faster-rcnn/data/test.record']
I0407 01:53:56.879946 140686801659776 dataset_builder.py:79] Reading record datasets for input file: ['/content/tensorflow-object-detection-faster-rcnn/data/test.record']
INFO:tensorflow:Number of filenames to read: 1
I0407 01:53:56.880086 14068680165

# Export Model

In [16]:
import re
import numpy as np

output_directory = './fine_tuned_model'

lst = os.listdir(model_dir)
lst = [l for l in lst if 'model.ckpt-' in l and '.meta' in l]
steps=np.array([int(re.findall('\d+', l)[0]) for l in lst])
last_model = lst[steps.argmax()].replace('.meta', '')

last_model_path = os.path.join(model_dir, last_model)
print(last_model_path)
!python /content/models/research/object_detection/export_inference_graph.py \
    --input_type=image_tensor \
    --pipeline_config_path={pipeline_fname} \
    --output_directory={output_directory} \
    --trained_checkpoint_prefix={last_model_path}

training/model.ckpt-500
Using TensorFlow backend.
Instructions for updating:
Please use `layer.__call__` method instead.
W0407 01:53:36.634775 140392554559360 deprecation.py:323] From /usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
INFO:tensorflow:depth of additional conv before box predictor: 0
I0407 01:53:38.618995 140392554559360 convolutional_box_predictor.py:155] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0407 01:53:38.655335 140392554559360 convolutional_box_predictor.py:155] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0407 01:53:38.691787 140392554559360 convolutional_box_predictor.py:155] depth of additional conv before box predicto

# Confusion Matrix

In [18]:
!python /content/models/research/object_detection/inference/infer_detections.py --input_tfrecord_paths=/content/tensorflow-object-detection-faster-rcnn/data/test.record --output_tfrecord_path=/content/detections.record --inference_graph=/content/models/research/fine_tuned_model/frozen_inference_graph.pb --discard_image_pixels

2022-04-07 02:00:37.948250: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2022-04-07 02:00:37.976989: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-07 02:00:37.977576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2022-04-07 02:00:37.977840: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2022-04-07 02:00:37.979828: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2022-04-07 02:00:37.980808: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2022-

In [19]:
!python /content/cf3.py --detections_record=/content/detections.record --label_map=/content/tensorflow-object-detection-faster-rcnn/data/label_map.pbtxt --output_path=/content/confusion_matrix3.csv


Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
W0407 02:00:57.302576 140056303228800 deprecation.py:323] From /content/cf3.py:38: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
Processed 100 images
Processed 100 images

Confusion Matrix:
[[ 0. 40.  7.]
 [ 0. 60.  4.]
 [ 0.  0.  0.]] 

[[ 0. 40.  7.]
 [ 0. 60.  4.]
 [ 0.  0.  0.]]
0.0
47.0
/content/cf3.py:118: RuntimeWarning: invalid value encountered in double_scalars
  precision = float(confusion_matrix[id, id] / total_predicted)
precision_Good@0.5IOU: nan
recall_Good@0.5IOU: 0.00
[[ 0. 40.  7.]
 [ 0. 60.  4.]
 [ 0.  0.  0.]]
100.0
64.0
precision_Bad@0.5IOU: 0.60
recall_Bad@0.5IOU: 0.94
  category  ...  recall_@0.5IOU
0     Good  ...          0.0000
1      Bad  ...          0.9375

[2 rows x 3 columns]


In [20]:
import pandas as pd
import tensorflow as tf

In [24]:
pdf=pd.DataFrame(columns=['score', 'label_idx', 'left', 'top', 'right', 'bottom', 'by', 'filename'])
example = tf.train.Example()
for record in tf.compat.v1.io.tf_record_iterator('/content/detections.record'):
    example.ParseFromString(record)
    f = example.features.feature
    score = f['image/detection/score'].float_list.value
    score = [x for x in score if x >= 0.20]
    l = len(score)
    pdf=pdf.append({'score': score,
                    'label_idx': f['image/detection/label'].int64_list.value[:l],
                    'left': f['image/detection/bbox/xmin'].float_list.value[:l],
                    'top': f['image/detection/bbox/ymin'].float_list.value[:l],
                    'right': f['image/detection/bbox/xmax'].float_list.value[:l],
                    'bottom': f['image/detection/bbox/ymax'].float_list.value[:l],
                    'filename': f['image/filename'].bytes_list.value[0].decode()}, ignore_index=True)

In [25]:
pdf.head()

score  \
0  [0.5410347580909729, 0.4609178304672241, 0.405...   
1  [0.5410341620445251, 0.460918128490448, 0.4050...   
2  [0.5410335063934326, 0.46091800928115845, 0.40...   
3  [0.5410363674163818, 0.46091583371162415, 0.40...   
4  [0.5410357713699341, 0.4609159529209137, 0.405...   

                                           label_idx  \
0  [2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, ...   
1  [2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, ...   
2  [2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, ...   
3  [2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, ...   
4  [2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, ...   

                                                left  \
0  [0.01421847939491272, 0.025623351335525513, 0....   
1  [0.014218300580978394, 0.025623470544815063, 0...   
2  [0.014218270778656006, 0.025623589754104614, 0...   
3  [0.01421821117401123, 0.02562326192855835, 0.0...   
4  [0.014218240976333618, 0.02562326192855835, 0....   

                                                 top  \
0  [0.01005101203918457, 0.020071029663085938, 0....   
1  [0.010051161050796509, 0.020070910453796387, 0...   
2  [0.010050922632217407, 0.020070791244506836, 0...   
3  [0.010051220655441284, 0.020071029663085938, 0...   
4  [0.010051161050796509, 0.020071029663085938, 0...   

                                               right  \
0  [0.9864640235900879, 0.9768209457397461, 0.481...   
1  [0.9864636659622192, 0.9768211841583252, 0.481...   
2  [0.9864636063575745, 0.9768208265304565, 0.481...   
3  [0.9864637851715088, 0.9768211245536804, 0.481...   
4  [0.9864639043807983, 0.9768211245536804, 0.481...   

                                              bottom   by filename  
0  [0.9880973696708679, 0.9808790683746338, 0.918...  NaN    1.png  
1  [0.9880971908569336, 0.9808790683746338, 0.918...  NaN   10.png  
2  [0.988097071647644, 0.9808793067932129, 0.9189...  NaN  100.png  
3  [0.9880973100662231, 0.9808790683746338, 0.918...  NaN   11.png  
4  [0.9880973100662231, 0.9808790683746338, 0.918...  NaN   12.png

In [26]:
pdf.shape

(100, 8)

In [31]:
pdf.to_csv('/content/Detections.csv')

In [27]:
!zip -r /content/models.zip /content/models/research/fine_tuned_model

  adding: content/models/research/fine_tuned_model/ (stored 0%)
  adding: content/models/research/fine_tuned_model/pipeline.config (deflated 70%)
  adding: content/models/research/fine_tuned_model/frozen_inference_graph.pb (deflated 10%)
  adding: content/models/research/fine_tuned_model/checkpoint (deflated 42%)
  adding: content/models/research/fine_tuned_model/eval_0/ (stored 0%)
  adding: content/models/research/fine_tuned_model/eval_0/pipeline.config (deflated 70%)
  adding: content/models/research/fine_tuned_model/eval_0/events.out.tfevents.1649296460.525be702b579 (deflated 11%)
  adding: content/models/research/fine_tuned_model/model.ckpt.meta (deflated 93%)
  adding: content/models/research/fine_tuned_model/model.ckpt.index (deflated 68%)
  adding: content/models/research/fine_tuned_model/saved_model/ (stored 0%)
  adding: content/models/research/fine_tuned_model/saved_model/variables/ (stored 0%)
  adding: content/models/research/fine_tuned_model/saved_model/saved_model.pb (de

In [28]:
!zip -r /content/trainvalandtest.zip /content/models/research/training

  adding: content/models/research/training/ (stored 0%)
  adding: content/models/research/training/model.ckpt-0.meta (deflated 93%)
  adding: content/models/research/training/model.ckpt-500.meta (deflated 93%)
  adding: content/models/research/training/model.ckpt-0.data-00000-of-00001 (deflated 55%)
  adding: content/models/research/training/graph.pbtxt (deflated 97%)
  adding: content/models/research/training/checkpoint (deflated 59%)
  adding: content/models/research/training/events.out.tfevents.1649295290.525be702b579 (deflated 93%)
  adding: content/models/research/training/eval_0/ (stored 0%)
  adding: content/models/research/training/eval_0/events.out.tfevents.1649295691.525be702b579 (deflated 35%)
  adding: content/models/research/training/eval_1/ (stored 0%)
  adding: content/models/research/training/eval_1/pipeline.config (deflated 67%)
  adding: content/models/research/training/eval_1/events.out.tfevents.1649295723.525be702b579 (deflated 11%)
  adding: content/models/research

In [29]:
import shutil
shutil.move("/content/models.zip", "/content/drive/MyDrive/SSD")
shutil.move("/content/trainvalandtest.zip", "/content/drive/MyDrive/SSD")

'/content/drive/MyDrive/SSD/trainvalandtest.zip'

In [ ]:
%load_ext tensorboard

In [ ]:
%tensorboard --logdir /content/models/research/training